id: P99A7F9F9
initial_creation_type: ocr
source_metadata:
  volumes:
    f2ff39ccdc08403397d25a827dfb2764:
      base_file: v050.txt
      image_group_id: I1PD95895
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ།
      total_pages: 1666
      volume_number: 50
